---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://gitlab.com/devopshq/gitlab-ci-linter
    rev: v1.0.3
    hooks:
      - id: gitlab-ci-linter

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
      - id: pylint
        exclude: tests
        additional_dependencies: [
          aiohttp==3.7.4,
          aiomysql,
          aioredis==1.3.1,
          aiosqlite,
          asyncpg,
          databases==0.4.3,
          motor==2.4.0,
          fastapi==0.63.0,
          fastapi_utils==0.2.1,
          pydantic==1.8.1,
          tortoise-orm==0.17.1,
          jmespath==0.10.0,
          pytest==6.2.3,
          sqlparse==0.4.1,
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: tests

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies: [
          fastapi==0.63.0,
          pydantic==1.8.1,
          tortoise-orm==0.17.1
        ]
